### ISSUE TITLE
Add option to check for existence of files during processing

### ISSUE THREAD

**Issue by BootBlock** [BootBlock/FileSieve#6]
_This report has been created by the [AppFramework framework](https://software.bootblock.co.uk/?id=biqubicsuite) on which the **FileSieve** application has been built and has been submitted with the user's express permission._
----
<details>
<summary>View submitted reported</summary>

#### APPLICATION INFORMATION ####
* **Version**: 4.57
* **Uptime**: 5 minutes(s), 31 seconds
* **Command Line**: D:\Program Files (x86)\FileSieve\FileSieve4.exe
* **Open Forms**
  * FS.Main.Forms.Main
      * **State**: Minimized
* **Loaded Assemblies**
  * `mscorlib`,  Version=4.0.0.0,  PublicKeyToken=b77a5c561934e089
  * `FileSieve4`,  Version=4.57.0.0
  * `System.Windows.Forms`,  Version=4.0.0.0,  PublicKeyToken=b77a5c561934e089
  * `System`,  Version=4.0.0.0,  PublicKeyToken=b77a5c561934e089
  * `System.Drawing`,  Version=4.0.0.0,  PublicKeyToken=b03f5f7f11d50a3a
  * `BiQubic.Framework`,  Version=2.0.0.0
  * `FileSieve4.Plugins`,  Version=4.57.0.0
  * `Microsoft.VisualBasic`,  Version=10.0.0.0,  PublicKeyToken=b03f5f7f11d50a3a
  * `System.Core`,  Version=4.0.0.0,  PublicKeyToken=b77a5c561934e089
  * `System.Web`,  Version=4.0.0.0,  PublicKeyToken=b03f5f7f11d50a3a
  * `System.Xml`,  Version=4.0.0.0,  PublicKeyToken=b77a5c561934e089
  * `System.Configuration`,  Version=4.0.0.0,  PublicKeyToken=b03f5f7f11d50a3a
  * `Accessibility`,  Version=4.0.0.0,  PublicKeyToken=b03f5f7f11d50a3a
  * `System.Management`,  Version=4.0.0.0,  PublicKeyToken=b03f5f7f11d50a3a
  * `Newtonsoft.Json`,  Version=12.0.0.0,  PublicKeyToken=30ad4fe6b2a6aeed
  * `System.Numerics`,  Version=4.0.0.0,  PublicKeyToken=b77a5c561934e089
  * `System.Runtime.Serialization`,  Version=4.0.0.0,  PublicKeyToken=b77a5c561934e089
  * `System.Data`,  Version=4.0.0.0,  PublicKeyToken=b77a5c561934e089
  * `Method.Attributes`,  Version=1.7.0.0
  * `Method.BatchedAtoZ`,  Version=1.0.0.0
  * `Method.Checksum`,  Version=1.0.0.0
  * `Method.Classification`,  Version=1.10.0.0
  * `Method.Consolidate`,  Version=1.5.0.0
  * `Method.DateStamp`,  Version=1.8.0.0
  * `Method.Delimiter`,  Version=1.0.0.0
  * `Method.Exif`,  Version=1.9.0.0
  * `Method.Extension`,  Version=1.5.0.0
  * `Method.FindReplace`,  Version=1.8.0.0
  * `Method.Mirror`,  Version=1.5.0.0
  * `Method.ParentRename`,  Version=1.1.0.0
  * `Method.Quantity`,  Version=1.6.0.0
  * `Method.StandardAtoZ`,  Version=1.7.0.0
  * `Method.Substring`,  Version=1.4.0.0
  * `Method.Tag`,  Version=1.14.0.0
  * `Modifier.Attributes`,  Version=1.7.0.0
  * `Modifier.Casing`,  Version=1.6.0.0
  * `Modifier.DateStamp`,  Version=1.2.0.0
  * `Modifier.FindReplace`,  Version=1.8.0.0
  * `Plugin.Registered`,  Version=4.54.0.10
  * `ExifLib`,  Version=1.7.0.0
  * `MantisSharp`,  Version=1.0.0.0

##### MESSAGE #####
* sourceFileName does not exist.

##### SOURCE #####
* BiQubic.Framework

##### TARGET SITE #####
* **Name**: Move
* **MemberType**: Method
* **Module**: BiQubic.Framework.dll

##### STACKTRACE #####
*    at FW.IO.File.Move(String sourceFileName, String destinationFileName)
*    at FS.Main.Core.Process.ProcessItem(SourceItem sourceItem, Item& item)
*    at FS.Main.Core.Process.Process\_ProcessSourceItems\_Stream()
*    at FS.Main.Core.Process.Process\_ProcessSourceItems()
*    at FS.Main.Core.Process.DoStart(Object value)
*    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
*    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
*    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
*    at System.Threading.ThreadHelper.ThreadStart(Object obj)

#### ADDITIONAL INFORMATION ####
* `Profiles.Count` = [1] '`1`'
* `Profile.Name` = [15] '`Default Profile`'
* `Profile.ActiveMethod.Name` = [9] '`DateStamp`'
* `Profile.ActiveMethod.NameExtended` = [53] '`DateStamp (Name Mask: %CREATED\_YEAR%-%CREATED\_MONTH%)`'
* `Profile.ActiveModifiers.Count` = [1] '`0`'
* `Profile.AllowedModes` = [20] '`Simulate, Copy, Move`'
* `Profile.CompleteAction` = [4] '`None`'
* `Profile.CopyMode` = [4] '`Move`'
* `Profile.EnsureSourceItemsExist` = [4] '`True`'
* `Profile.OverwriteNoMatchAction` = [6] '`Ignore`'
* `Profile.OverwriteOptions.HashAlgorithm` = [4] '`Sha1`'
* `Profile.OverwriteOptions.MetadataFields` = [8] '`FileName`'
* `Profile.OverwriteOptions.ComparisonMethod` = [8] '`Metadata`'
* `Profile.OverwriteRules.Count` = [1] '`1`'
* `Profile.OverwriteRules[0].Action` = [15] '`RenameUsingMask`'
* `Profile.OverwriteRules[0].Field` = [24] '`NewPathFilenameExtension`'
* `Profile.OverwriteRules[0].IsEnabled` = [4] '`True`'
* `Profile.OverwriteRules[0].RegEx` = [2] '`.\*`'
* `Profile.OverwriteRules[0].RenameMask` = [38] '`%file\_name% (%file\_number%).%file\_ext%`'
* `Profile.SourceItems[0].Name` = [13] '`DigitalCamera`'
* `Profile.SourceItems[0].DeleteEmptySubFolders` = [5] '`False`'
* `Profile.SourceItems[0].EnsureExists` = [4] '`Auto`'
* `Profile.SourceItems[0].GetFilesMode` = [5] '`Burst`'
* `Profile.SourceItems[0].IgnoreFilter` = [3] '`All`'
* `Profile.SourceItems[0].Items.Count` = [1] '`0`'
* `Profile.SourceItems[0].MaximumFilesize` = [2] '`-1`'
* `Profile.SourceItems[0].MinimumFilesize` = [1] '`0`'
* `Profile.SourceItems[0].RegExOptions` = [22] '`IgnoreCase, Singleline`'
* `Profile.SourceItems[0].RegexPatterns.Count` = [1] '`1`'
* `Profile.SourceItems[0].RulesType` = [9] '`Immediate`'
* `Profile.SourceItems[0].SearchFilter` = [3] '`All`'
* `Profile.SourceItems[0].SearchOption` = [14] '`AllDirectories`'
* `Profile.SourceItems[0].SearchPatternFileItems` = [2] '`.\*`'
* `Profile.Triggers.Count` = [1] '`0`'
* `Profile.ShowInWindowsExplorer` = [4] '`True`'
* `Profile.WasUpgraded` = [5] '`False`'

#### APPFRAMEWORK INFORMATION ####
* **Version**: 2
* **Languages**: Yes
* **LaunchCount**: 3
* **TotalDuration**: 00:00:00

#### SYSTEM INFORMATION ####
* **ID**: AC1B192AB0940AAA17B301E127A9A2835C9A46E3
* **Operating System:** Microsoft Windows 10 Pro (6.2.9200.0; Win32NT; x64)
* **Physical Memory:** 54,993 MB free of 65,444 MB
* **Virtual Memory:** 134,212,816 MB free of 134,217,727 MB
* **Working Set:** 192 MB
* **CPUs:** 12

#### ENVIRONMENT ####
* **Displays:** 3440x1440x32 (3440x1400)*, 1920x1080x32 (1920x1040)
* **.NET Frameworks:** 2.0, 3.0, 3.5, 4 Client, 4 Full
* **.NET Version:** 4.0.30319.42000
* **Culture:** en-US (English (United States))
* **Input Language:** en-US (US)
* **VisualStyles:** Enabled

#### APPFRAMEWORK LOG ####
* [**11/25/2020 at 5:49:59 PM**] Startup `Information` FileSieve v4.57.0.0
* [**11/25/2020 at 5:49:59 PM**] Startup `Information`     OS: Microsoft Windows 10 Pro 6.2.9200.0 (Win32NT; x64). CPUs: 12.
* [**11/25/2020 at 5:49:59 PM**] Startup `Information`     Memory: 53.47GB of 63.91GB free.
* [**11/25/2020 at 5:49:59 PM**] Startup `Information`     UI Culture: English (United States)
* 
* [**11/25/2020 at 5:49:59 PM**] Startup `Debug` Exception handler has been initialised to use MantisBT.
* [**11/25/2020 at 5:50:00 PM**] Plugins `Debug` Found plugins: Method.Attributes.dll, Method.BatchedAtoZ.dll, Method.Checksum.dll, Method.Classification.dll, Method.Consolidate.dll, Method.DateStamp.dll, Method.Delimiter.dll, Method.Exif.dll, Method.Extension.dll, Method.FindReplace.dll, Method.Mirror.dll, Method.ParentRename.dll, Method.Quantity.dll, Method.StandardAtoZ.dll, Method.Substring.dll, Method.Tag.dll, Modifier.Attributes.dll, Modifier.Casing.dll, Modifier.DateStamp.dll, Modifier.FindReplace.dll, Plugin.Registered.dll
* [**11/25/2020 at 5:50:00 PM**] Plugins `Verbose` Available Triggers: DateTime, Directory Watcher, User Idle
* [**11/25/2020 at 5:50:00 PM**] Plugins `Verbose` Attributes initialised OK.
* [**11/25/2020 at 5:50:00 PM**] Plugins `Verbose` Batched A-Z initialised OK.
* [**11/25/2020 at 5:50:00 PM**] Plugins `Verbose` Checksum initialised OK.
* [**11/25/2020 at 5:50:00 PM**] Plugins `Verbose` Classification initialised OK.
* [**11/25/2020 at 5:50:00 PM**] Plugins `Verbose` Consolidate initialised OK.
* [**11/25/2020 at 5:50:00 PM**] Plugins `Verbose` DateStamp initialised OK.
* [**11/25/2020 at 5:50:00 PM**] Plugins `Verbose` Delimiter initialised OK.
* [**11/25/2020 at 5:50:00 PM**] Plugins `Verbose` EXIF initialised OK.
* [**11/25/2020 at 5:50:00 PM**] Plugins `Verbose` Extension initialised OK.
* [**11/25/2020 at 5:50:00 PM**] Plugins `Verbose` Find Replace initialised OK.
* [**11/25/2020 at 5:50:00 PM**] Plugins `Verbose` Mirror initialised OK.
* [**11/25/2020 at 5:50:00 PM**] Plugins `Verbose` Parent Rename initialised OK.
* [**11/25/2020 at 5:50:00 PM**] Plugins `Verbose` Quantity initialised OK.
* [**11/25/2020 at 5:50:00 PM**] Plugins `Verbose` Standard A-Z initialised OK.
* [**11/25/2020 at 5:50:00 PM**] Plugins `Verbose` Substring initialised OK.
* [**11/25/2020 at 5:50:00 PM**] Plugins `Verbose` Tag initialised OK.
* [**11/25/2020 at 5:50:00 PM**] Plugins `Verbose` Attributes initialised OK.
* [**11/25/2020 at 5:50:00 PM**] Plugins `Verbose` Casing initialised OK.
* [**11/25/2020 at 5:50:00 PM**] Plugins `Verbose` DateStamp initialised OK.
* [**11/25/2020 at 5:50:00 PM**] Plugins `Verbose` Find Replace initialised OK.
* [**11/25/2020 at 5:50:00 PM**] Plugins `Verbose` Registered initialised OK.
* 
* [**11/25/2020 at 5:50:19 PM**] Process.Start `Information` Profile: Default Profile
* [**11/25/2020 at 5:50:19 PM**] Process.Start `Information`   Mode: Move
* [**11/25/2020 at 5:50:19 PM**] Process.Start `Information`   Method: DateStamp
* [**11/25/2020 at 5:50:19 PM**] Process.Start `Information`   Source Items: 1
* [**11/25/2020 at 5:50:19 PM**] Process.Start `Information`   Destination: \\nas1\photo
* [**11/25/2020 at 5:50:19 PM**] Process.Start `Information`   DestinationEncoded: \\nas1\photo
* [**11/25/2020 at 5:50:19 PM**] Process.Start `Information`   Overwrite Options: Metadata: FileName
* [**11/25/2020 at 5:50:19 PM**] Process.Start `Information`   Overwrite Rules: NewPathFilenameExtension -\> RenameUsingMask
* [**11/25/2020 at 5:50:19 PM**] Process.Start `Information`   Overwrite Fallback: Ignore
* [**11/25/2020 at 5:50:19 PM**] Process.Start `Information` Preparing to process items.
* [**11/25/2020 at 5:50:19 PM**]  `Debug` Told Windows that it shouldn't shutdown while we're actively processing a Profile.
* [**11/25/2020 at 5:50:19 PM**] Process.DoStart `Debug` Before Processing Statistics
* [**11/25/2020 at 5:50:19 PM**] Process.DoStart `Debug`     Threads: 17
* [**11/25/2020 at 5:50:19 PM**] Process.DoStart `Debug`     Base Priority: 8
* [**11/25/2020 at 5:50:19 PM**] Process.DoStart `Debug`     Priority Class: Normal
* [**11/25/2020 at 5:50:19 PM**] Process.DoStart `Debug`     User CPU Time: 00:00:01.4218750
* [**11/25/2020 at 5:50:19 PM**] Process.DoStart `Debug`     Total CPU Time: 00:00:03.3593750
* [**11/25/2020 at 5:50:19 PM**] Process.DoStart `Debug`     Paged System Memory Size: 660 KB
* [**11/25/2020 at 5:50:19 PM**] Process.DoStart `Debug`     Non-paged System Memory Size: 43 KB
* [**11/25/2020 at 5:50:19 PM**] Process.DoStart `Debug`     Paged Memory Size: 60 MB
* [**11/25/2020 at 5:50:19 PM**] Process.DoStart `Debug`     Peak Paged Memory Size: 61 MB
* [**11/25/2020 at 5:50:19 PM**] Process.DoStart `Debug`     Working Set: 88 MB
* [**11/25/2020 at 5:50:19 PM**] Process.DoStart `Debug`     Peak Working Set: 88 MB
* [**11/25/2020 at 5:50:19 PM**] Process.DoStart `Debug`     Private Memory Size: 60 MB
* [**11/25/2020 at 5:50:19 PM**] Process.DoStart `Debug`     Virtual Memory Size: 4.78 GB
* [**11/25/2020 at 5:50:19 PM**] Process.DoStart `Debug`     Peak Virtual Memory Size: 4.78 GB
* 
* [**11/25/2020 at 5:51:27 PM**] Process.Process\_GetSourceItems `Information` Pre-scan Time: 68.2410133 seconds.
* [**11/25/2020 at 5:51:27 PM**] Process.DoStart `Information` Found 110,682 items for processing.
* [**11/25/2020 at 5:51:27 PM**] Process.DoStart `Information` Processing items...
* [**11/25/2020 at 5:51:27 PM**] Process.ProcessSourceItems `Information` The Processing Engine has been set to Stream mode by the DateStamp method.
* [**11/25/2020 at 5:51:36 PM**] Process.ProcessItem `Debug` Created directory '\\nas1\photo\2020-11'
* [**11/25/2020 at 5:51:45 PM**] Process.ProcessItem `Debug` Created directory '\\nas1\photo\2020-10'
* [**11/25/2020 at 5:52:01 PM**] Process.ProcessItem `Debug` Created directory '\\nas1\photo\2020-09'
* [**11/25/2020 at 5:52:19 PM**] Process.ProcessItem `Debug` Created directory '\\nas1\photo\2020-08'
* [**11/25/2020 at 5:52:33 PM**] Process.ProcessItem `Debug` Created directory '\\nas1\photo\2020-07'
* [**11/25/2020 at 5:52:39 PM**] Process.ProcessItem `Debug` Created directory '\\nas1\photo\2020-06'
* [**11/25/2020 at 5:52:41 PM**] Process.ProcessItem `Debug` Created directory '\\nas1\photo\2020-04'
* [**11/25/2020 at 5:52:44 PM**] Process.ProcessItem `Debug` Created directory '\\nas1\photo\2020-03'
* [**11/25/2020 at 5:52:46 PM**] Process.ProcessItem `Debug` Created directory '\\nas1\photo\2020-02'
* [**11/25/2020 at 5:52:48 PM**] Process.ProcessItem `Debug` Created directory '\\nas1\photo\2020-01'
* [**11/25/2020 at 5:52:51 PM**] Process.ProcessItem `Debug` Created directory '\\nas1\photo\2019-12'
* [**11/25/2020 at 5:53:00 PM**] Process.ProcessItem `Debug` Created directory '\\nas1\photo\2019-10'
* [**11/25/2020 at 5:53:01 PM**] Process.ProcessItem `Debug` Created directory '\\nas1\photo\2019-09'
* [**11/25/2020 at 5:53:03 PM**] Process.ProcessItem `Debug` Created directory '\\nas1\photo\2019-08'
* [**11/25/2020 at 5:53:05 PM**] Process.ProcessItem `Debug` Created directory '\\nas1\photo\2019-07'
* [**11/25/2020 at 5:53:08 PM**] Process.ProcessItem `Debug` Created directory '\\nas1\photo\2019-06'
* [**11/25/2020 at 5:53:08 PM**] Process.ProcessItem `Debug` Created directory '\\nas1\photo\2019-05'
* [**11/25/2020 at 5:53:09 PM**] Process.ProcessItem `Debug` Created directory '\\nas1\photo\2019-04'
* [**11/25/2020 at 5:53:11 PM**] Process.ProcessItem `Debug` Created directory '\\nas1\photo\2019-03'
* [**11/25/2020 at 5:53:15 PM**] Process.ProcessItem `Debug` Created directory '\\nas1\photo\2019-02'
* [**11/25/2020 at 5:53:19 PM**] Process.ProcessItem `Debug` Created directory '\\nas1\photo\2019-01'
* [**11/25/2020 at 5:53:20 PM**] Process.ProcessItem `Debug` Created directory '\\nas1\photo\2018-12'
* [**11/25/2020 at 5:53:22 PM**] Process.ProcessItem `Debug` Created directory '\\nas1\photo\2018-11'
* [**11/25/2020 at 5:53:23 PM**] Process.ProcessItem `Debug` Created directory '\\nas1\photo\2018-08'
* [**11/25/2020 at 5:53:23 PM**] Process.ProcessItem `Debug` Created directory '\\nas1\photo\2018-07'
* [**11/25/2020 at 5:53:23 PM**] Process.ProcessItem `Debug` Created directory '\\nas1\photo\2018-06'
* [**11/25/2020 at 5:53:24 PM**] Process.ProcessItem `Debug` Created directory '\\nas1\photo\2018-03'
* [**11/25/2020 at 5:53:27 PM**] Process.ProcessItem `Debug` Created directory '\\nas1\photo\2018-02'
* [**11/25/2020 at 5:53:33 PM**] Process.ProcessItem `Debug` Created directory '\\nas1\photo\2018-01'
* [**11/25/2020 at 5:53:37 PM**] Process.ProcessItem `Debug` Created directory '\\nas1\photo\2017-12'
* [**11/25/2020 at 5:53:40 PM**] Process.ProcessItem `Debug` Created directory '\\nas1\photo\2017-11'
* [**11/25/2020 at 5:53:40 PM**] Process.ProcessItem `Debug` Created directory '\\nas1\photo\2017-10'
* [**11/25/2020 at 5:53:40 PM**] Process.ProcessItem `Debug` Created directory '\\nas1\photo\2017-08'
* [**11/25/2020 at 5:53:40 PM**] Process.ProcessItem `Debug` Created directory '\\nas1\photo\2012-01'
* [**11/25/2020 at 5:53:40 PM**] Process.ProcessItem `Debug` Created directory '\\nas1\photo\2009-01'
* [**11/25/2020 at 5:55:31 PM**] AppFramework `Fatal` A domain exception has been caught: sourceFileName does not exist.
</details>

**Comment by BootBlock** [comment]
Thanks for the report!

It appears the source file no longer exists since the initial file scanning was performed and when it came to actually copying/moving the file. I've added a check so now a file's existence is queried before the copying/moving is performed; this results in an extra I/O operation so I've added a `CheckForFileExistenceBeforeProcessing` flag to Settings - Advanced so it can be optionally disabled. (no perf loss on SSD/NVMe drives)

**Comment by BootBlock** [comment]
**Update:** `CheckForFileExistenceBeforeProcessing` has been moved into the Source Item Editor so it can be disabled on a per-Source Item basis. This allows it to be enabled on fast drives but (manually) disabled on slow ones.

![fs4-advanced-fileexistencecheck](https://user-images.githubusercontent.com/18527642/106058975-e5900700-60e9-11eb-9b7a-eeaf698b0616.png)
