### ISSUE TITLE
Exception: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by BootBlock** [BootBlock/FileSieve#68]
_This report has been created by the [AppFramework framework](https://software.bootblock.co.uk/?id=biqubicsuite) on which the **FileSieve** application has been built.
This report has been submitted with the user's express permission._

<details>
<summary>View submitted report</summary>

#### APPLICATION INFORMATION ####
* **Version**: 4.57
* **Uptime**: 27 minutes(s), 55 seconds
* **Command Line**: C:\Program Files (x86)\FileSieve\FileSieve4.exe
* **Open Forms**
  * FS.Main.Forms.Main
* **Loaded Assemblies**
  * `mscorlib`,  Version=4.0.0.0,  PublicKeyToken=b77a5c561934e089
  * `FileSieve4`,  Version=4.57.0.0
  * `System.Windows.Forms`,  Version=4.0.0.0,  PublicKeyToken=b77a5c561934e089
  * `System`,  Version=4.0.0.0,  PublicKeyToken=b77a5c561934e089
  * `System.Drawing`,  Version=4.0.0.0,  PublicKeyToken=b03f5f7f11d50a3a
  * `BiQubic.Framework`,  Version=2.0.0.0
  * `FileSieve4.Plugins`,  Version=4.57.0.0
  * `Microsoft.VisualBasic`,  Version=10.0.0.0,  PublicKeyToken=b03f5f7f11d50a3a
  * `System.Core`,  Version=4.0.0.0,  PublicKeyToken=b77a5c561934e089
  * `System.Web`,  Version=4.0.0.0,  PublicKeyToken=b03f5f7f11d50a3a
  * `System.Xml`,  Version=4.0.0.0,  PublicKeyToken=b77a5c561934e089
  * `System.Configuration`,  Version=4.0.0.0,  PublicKeyToken=b03f5f7f11d50a3a
  * `Accessibility`,  Version=4.0.0.0,  PublicKeyToken=b03f5f7f11d50a3a
  * `System.Management`,  Version=4.0.0.0,  PublicKeyToken=b03f5f7f11d50a3a
  * `Newtonsoft.Json`,  Version=12.0.0.0,  PublicKeyToken=30ad4fe6b2a6aeed
  * `System.Numerics`,  Version=4.0.0.0,  PublicKeyToken=b77a5c561934e089
  * `System.Runtime.Serialization`,  Version=4.0.0.0,  PublicKeyToken=b77a5c561934e089
  * `System.Data`,  Version=4.0.0.0,  PublicKeyToken=b77a5c561934e089
  * `Method.Attributes`,  Version=1.7.0.0
  * `Method.BatchedAtoZ`,  Version=1.0.0.0
  * `Method.Checksum`,  Version=1.0.0.0
  * `Method.Classification`,  Version=1.10.0.0
  * `Method.Consolidate`,  Version=1.5.0.0
  * `Method.DateStamp`,  Version=1.8.0.0
  * `Method.Delimiter`,  Version=1.0.0.0
  * `Method.Exif`,  Version=1.9.0.0
  * `Method.Extension`,  Version=1.5.0.0
  * `Method.FindReplace`,  Version=1.8.0.0
  * `Method.Mirror`,  Version=1.5.0.0
  * `Method.ParentRename`,  Version=1.1.0.0
  * `Method.Quantity`,  Version=1.6.0.0
  * `Method.StandardAtoZ`,  Version=1.7.0.0
  * `Method.Substring`,  Version=1.4.0.0
  * `Method.Tag`,  Version=1.14.0.0
  * `Modifier.Attributes`,  Version=1.7.0.0
  * `Modifier.Casing`,  Version=1.6.0.0
  * `Modifier.DateStamp`,  Version=1.2.0.0
  * `Modifier.FindReplace`,  Version=1.8.0.0
  * `ExifLib`,  Version=1.7.0.0
  * `MantisSharp`,  Version=1.0.0.0

##### MESSAGE #####
* Object reference not set to an instance of an object.

##### SOURCE #####
* FileSieve4

##### TARGET SITE #####
* **Name**: Process\_ProcessSourceItems\_Stream
* **MemberType**: Method
* **Module**: FileSieve4.exe

##### STACKTRACE #####
*    at FS.Main.Core.Process.Process\_ProcessSourceItems\_Stream()
*    at FS.Main.Core.Process.Process\_ProcessSourceItems()
*    at FS.Main.Core.Process.DoStart(Object value)
*    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
*    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
*    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
*    at System.Threading.ThreadHelper.ThreadStart(Object obj)

#### ADDITIONAL INFORMATION ####
* `Profiles.Count` = [1] '`1`'
* `Profile.Name` = [15] '`Default Profile`'
* `Profile.ActiveMethod.Name` = [9] '`DateStamp`'
* `Profile.ActiveMethod.NameExtended` = [67] '`DateStamp (Name Mask: %WRITTEN\_YEAR%\_%WRITTEN\_MONTH%\_%WRITTEN\_DAY%)`'
* `Profile.ActiveModifiers.Count` = [1] '`0`'
* `Profile.AllowedModes` = [20] '`Simulate, Copy, Move`'
* `Profile.CompleteAction` = [4] '`None`'
* `Profile.CopyMode` = [8] '`Simulate`'
* `Profile.EnsureSourceItemsExist` = [4] '`True`'
* `Profile.OverwriteNoMatchAction` = [6] '`Ignore`'
* `Profile.OverwriteOptions.HashAlgorithm` = [4] '`Sha1`'
* `Profile.OverwriteOptions.MetadataFields` = [8] '`FileName`'
* `Profile.OverwriteOptions.ComparisonMethod` = [8] '`Metadata`'
* `Profile.OverwriteRules.Count` = [1] '`1`'
* `Profile.OverwriteRules[0].Action` = [15] '`RenameUsingMask`'
* `Profile.OverwriteRules[0].Field` = [24] '`NewPathFilenameExtension`'
* `Profile.OverwriteRules[0].IsEnabled` = [4] '`True`'
* `Profile.OverwriteRules[0].RegEx` = [2] '`.\*`'
* `Profile.OverwriteRules[0].RenameMask` = [38] '`%file\_name% (%file\_number%).%file\_ext%`'
* `Profile.SourceItems[0].Name` = [8] '`pictures`'
* `Profile.SourceItems[0].DeleteEmptySubFolders` = [5] '`False`'
* `Profile.SourceItems[0].EnsureExists` = [4] '`True`'
* `Profile.SourceItems[0].GetFilesMode` = [5] '`Burst`'
* `Profile.SourceItems[0].IgnoreFilter` = [3] '`All`'
* `Profile.SourceItems[0].Items.Count` = [1] '`0`'
* `Profile.SourceItems[0].MaximumFilesize` = [2] '`-1`'
* `Profile.SourceItems[0].MinimumFilesize` = [1] '`0`'
* `Profile.SourceItems[0].RegExOptions` = [22] '`IgnoreCase, Singleline`'
* `Profile.SourceItems[0].RegexPatterns.Count` = [1] '`1`'
* `Profile.SourceItems[0].RulesType` = [9] '`Immediate`'
* `Profile.SourceItems[0].SearchFilter` = [3] '`All`'
* `Profile.SourceItems[0].SearchOption` = [14] '`AllDirectories`'
* `Profile.SourceItems[0].SearchPatternFileItems` = [2] '`.\*`'
* `Profile.SourceItems[1].Name` = [6] '`videos`'
* `Profile.SourceItems[1].DeleteEmptySubFolders` = [5] '`False`'
* `Profile.SourceItems[1].EnsureExists` = [4] '`Auto`'
* `Profile.SourceItems[1].GetFilesMode` = [5] '`Burst`'
* `Profile.SourceItems[1].IgnoreFilter` = [3] '`All`'
* `Profile.SourceItems[1].Items.Count` = [1] '`?`'
* `Profile.SourceItems[1].MaximumFilesize` = [2] '`-1`'
* `Profile.SourceItems[1].MinimumFilesize` = [1] '`0`'
* `Profile.SourceItems[1].RegExOptions` = [22] '`IgnoreCase, Singleline`'
* `Profile.SourceItems[1].RegexPatterns.Count` = [1] '`1`'
* `Profile.SourceItems[1].RulesType` = [9] '`Immediate`'
* `Profile.SourceItems[1].SearchFilter` = [3] '`All`'
* `Profile.SourceItems[1].SearchOption` = [14] '`AllDirectories`'
* `Profile.SourceItems[1].SearchPatternFileItems` = [2] '`.\*`'
* `Profile.Triggers.Count` = [1] '`0`'
* `Profile.ShowInWindowsExplorer` = [4] '`True`'
* `Profile.WasUpgraded` = [5] '`False`'

#### APPFRAMEWORK INFORMATION ####
* **Version**: 2
* **Languages**: Yes
* **LaunchCount**: 5
* **TotalDuration**: 00:00:00

#### SYSTEM INFORMATION ####
* **ID**: 501EBA3DC7771B3DA9E3224BF328FCBC9813CC47
* **Operating System:** Microsoft Windows 10 Home (6.2.9200.0; Win32NT; x64)
* **Physical Memory:** 3,243 MB free of 8,001 MB
* **Virtual Memory:** 134,212,808 MB free of 134,217,727 MB
* **Working Set:** 106 MB
* **CPUs:** 8
* **Battery Status:** 0 at `0.42%`

#### ENVIRONMENT ####
* **Displays:** 1536x864x32 (1536x834)
* **.NET Frameworks:** 2.0, 3.0, 3.5, 4 Client, 4 Full
* **.NET Version:** 4.0.30319.42000
* **Culture:** en-US (English (United States))
* **Input Language:** en-US (US)
* **VisualStyles:** Enabled

#### APPFRAMEWORK LOG ####
* [**1/18/2021 at 8:33:11 PM**] Startup `Information` FileSieve v4.57.0.0
* [**1/18/2021 at 8:33:12 PM**] Startup `Information`     OS: Microsoft Windows 10 Home 6.2.9200.0 (Win32NT; x64). CPUs: 8.
* [**1/18/2021 at 8:33:12 PM**] Startup `Information`     Memory: 3.31GB of 7.81GB free.
* [**1/18/2021 at 8:33:12 PM**] Startup `Information`     UI Culture: English (United States)
* 
* [**1/18/2021 at 8:33:12 PM**] Startup `Debug` Exception handler has been initialised to use MantisBT.
* [**1/18/2021 at 8:33:12 PM**] Plugins `Debug` Found plugins: Method.Attributes.dll, Method.BatchedAtoZ.dll, Method.Checksum.dll, Method.Classification.dll, Method.Consolidate.dll, Method.DateStamp.dll, Method.Delimiter.dll, Method.Exif.dll, Method.Extension.dll, Method.FindReplace.dll, Method.Mirror.dll, Method.ParentRename.dll, Method.Quantity.dll, Method.StandardAtoZ.dll, Method.Substring.dll, Method.Tag.dll, Modifier.Attributes.dll, Modifier.Casing.dll, Modifier.DateStamp.dll, Modifier.FindReplace.dll
* [**1/18/2021 at 8:33:12 PM**] Plugins `Verbose` Available Triggers: DateTime, Directory Watcher, User Idle
* [**1/18/2021 at 8:33:12 PM**] Plugins `Verbose` Attributes initialised OK.
* [**1/18/2021 at 8:33:12 PM**] Plugins `Verbose` Batched A-Z initialised OK.
* [**1/18/2021 at 8:33:12 PM**] Plugins `Verbose` Checksum initialised OK.
* [**1/18/2021 at 8:33:12 PM**] Plugins `Verbose` Classification initialised OK.
* [**1/18/2021 at 8:33:12 PM**] Plugins `Verbose` Consolidate initialised OK.
* [**1/18/2021 at 8:33:12 PM**] Plugins `Verbose` DateStamp initialised OK.
* [**1/18/2021 at 8:33:12 PM**] Plugins `Verbose` Delimiter initialised OK.
* [**1/18/2021 at 8:33:13 PM**] Plugins `Verbose` EXIF initialised OK.
* [**1/18/2021 at 8:33:13 PM**] Plugins `Verbose` Extension initialised OK.
* [**1/18/2021 at 8:33:13 PM**] Plugins `Verbose` Find Replace initialised OK.
* [**1/18/2021 at 8:33:13 PM**] Plugins `Verbose` Mirror initialised OK.
* [**1/18/2021 at 8:33:13 PM**] Plugins `Verbose` Parent Rename initialised OK.
* [**1/18/2021 at 8:33:13 PM**] Plugins `Verbose` Quantity initialised OK.
* [**1/18/2021 at 8:33:13 PM**] Plugins `Verbose` Standard A-Z initialised OK.
* [**1/18/2021 at 8:33:13 PM**] Plugins `Verbose` Substring initialised OK.
* [**1/18/2021 at 8:33:13 PM**] Plugins `Verbose` Tag initialised OK.
* [**1/18/2021 at 8:33:13 PM**] Plugins `Verbose` Attributes initialised OK.
* [**1/18/2021 at 8:33:13 PM**] Plugins `Verbose` Casing initialised OK.
* [**1/18/2021 at 8:33:13 PM**] Plugins `Verbose` DateStamp initialised OK.
* [**1/18/2021 at 8:33:13 PM**] Plugins `Verbose` Find Replace initialised OK.
* 
* [**1/18/2021 at 9:01:08 PM**] Process.Start `Information` Profile: Default Profile
* [**1/18/2021 at 9:01:08 PM**] Process.Start `Information`   Mode: Simulate
* [**1/18/2021 at 9:01:08 PM**] Process.Start `Information`   Method: DateStamp
* [**1/18/2021 at 9:01:08 PM**] Process.Start `Information`   Source Items: 2
* [**1/18/2021 at 9:01:08 PM**] Process.Start `Information`   Destination: C:\Users\user\Pictures\User iPhone\reorg\pictures
* [**1/18/2021 at 9:01:08 PM**] Process.Start `Information`   DestinationEncoded: C:\Users\user\Pictures\User iPhone\reorg\pictures
* [**1/18/2021 at 9:01:08 PM**] Process.Start `Information`   Overwrite Options: Metadata: FileName
* [**1/18/2021 at 9:01:08 PM**] Process.Start `Information`   Overwrite Rules: NewPathFilenameExtension -\> RenameUsingMask
* [**1/18/2021 at 9:01:08 PM**] Process.Start `Information`   Overwrite Fallback: Ignore
* [**1/18/2021 at 9:01:08 PM**] Process.Start `Information` Preparing to process items.
* [**1/18/2021 at 9:01:08 PM**]  `Debug` Told Windows that it shouldn't shutdown while we're actively processing a Profile.
* [**1/18/2021 at 9:01:08 PM**] Process.DoStart `Debug` Before Processing Statistics
* [**1/18/2021 at 9:01:08 PM**] Process.DoStart `Debug`     Threads: 10
* [**1/18/2021 at 9:01:08 PM**] Process.DoStart `Debug`     Base Priority: 13
* [**1/18/2021 at 9:01:08 PM**] Process.DoStart `Debug`     Priority Class: High
* [**1/18/2021 at 9:01:08 PM**] Process.DoStart `Debug`     User CPU Time: 00:00:04.7031250
* [**1/18/2021 at 9:01:08 PM**] Process.DoStart `Debug`     Total CPU Time: 00:00:08.9375000
* [**1/18/2021 at 9:01:08 PM**] Process.DoStart `Debug`     Paged System Memory Size: 685 KB
* [**1/18/2021 at 9:01:08 PM**] Process.DoStart `Debug`     Non-paged System Memory Size: 55 KB
* [**1/18/2021 at 9:01:08 PM**] Process.DoStart `Debug`     Paged Memory Size: 61 MB
* [**1/18/2021 at 9:01:08 PM**] Process.DoStart `Debug`     Peak Paged Memory Size: 69 MB
* [**1/18/2021 at 9:01:08 PM**] Process.DoStart `Debug`     Working Set: 98 MB
* [**1/18/2021 at 9:01:08 PM**] Process.DoStart `Debug`     Peak Working Set: 106 MB
* [**1/18/2021 at 9:01:08 PM**] Process.DoStart `Debug`     Private Memory Size: 61 MB
* [**1/18/2021 at 9:01:08 PM**] Process.DoStart `Debug`     Virtual Memory Size: 4.78 GB
* [**1/18/2021 at 9:01:08 PM**] Process.DoStart `Debug`     Peak Virtual Memory Size: 4.82 GB
* 
* [**1/18/2021 at 9:01:08 PM**] Process\_GetSourceItems `Warning` Reached the Free version Item limit of 200. Skipping ahead.
* [**1/18/2021 at 9:01:08 PM**] Process.Process\_GetSourceItems `Information` Pre-scan Time: 0.2585094 seconds.
* [**1/18/2021 at 9:01:08 PM**] Process.DoStart `Information` Found 290 items for processing.
* [**1/18/2021 at 9:01:08 PM**] Process.DoStart `Information` Processing items...
* [**1/18/2021 at 9:01:08 PM**] Process.ProcessSourceItems `Information` The Processing Engine has been set to Stream mode by the DateStamp method.
* [**1/18/2021 at 9:01:08 PM**] AppFramework `Fatal` A domain exception has been caught: Object reference not set to an instance of an object.
</details>

**Comment by BootBlock** [comment]
Thanks for reporting this issue.

An attempt at fixing this has been made, but it's a bit of a _hopefully this was the problem_ type of fix as unfortunately the report doesn't include enough information on exactly what the issue is. This is a fault on my part; in a future update, FileSieve will include further information in reports to help narrow down crashes.
